name: Deploy MEAN Stack to EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PUBLIC_IP: 3.86.84.57
  PRIVATE_IP: 172.31.95.75
  NODE_ENV: production

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Angular CLI
      run: |
        sudo npm install -g @angular/cli
        
    - name: Install Frontend Dependencies
      run: |
        npm ci --legacy-peer-deps
        
    - name: Build Angular App
      run: |
        ng build --configuration=production
        
    - name: Install Backend Dependencies
      working-directory: ./backend
      run: |
        npm ci
        
    - name: Setup PM2
      run: |
        sudo npm install -g pm2
        
    - name: Deploy Application
      run: |
        # Stop existing processes
        pm2 stop all || true
        
        # Create necessary directories
        sudo mkdir -p /var/www/html/angular-app
        sudo mkdir -p /var/www/backend
        
        # Deploy Angular frontend
        sudo rm -rf /var/www/html/angular-app/*
        sudo cp -r dist/alinoj/* /var/www/html/angular-app/
        
        # Deploy Node.js backend
        sudo rm -rf /var/www/backend/*
        sudo cp -r backend/* /var/www/backend/
        
        # Set proper permissions
        sudo chown -R ubuntu:ubuntu /var/www/backend
        sudo chown -R ubuntu:ubuntu /var/www/html/angular-app
        
        # Start backend application with PM2
        cd /var/www/backend
        pm2 start app.js --name "mean-backend"
        pm2 save
        
    - name: Verify Deployment
      run: |
        # Check if backend is running
        pm2 status
        # Check if nginx is running
        sudo systemctl status nginx